### PR TITLE
Adding Aurelia aurelia-app and aurelia-main properties to Intellisense.

### PR DESCRIPTION
**Pull request by AshleyGrant**

### CODE REVIEW

**Comment by madskristensen** [comment]
Awesome. thanks

**Comment by AshleyGrant** [comment]
Should I open an issue on the WS2013 repo to remind you to backport this?

**Comment by madskristensen** [comment]
that would be great, thanks

**Comment by madskristensen** [comment]
If you want to test the latest build that includes this PR, then you can find it here http://vsixgallery.com/extension/5fb7364d-2e8c-44a4-95eb-2a382e30fec9/

**Comment by AshleyGrant** [comment]
Awesome. I'll install it. I've also posted it to the Aurelia gitter channel for them to test.

**Pull request merged**
